build:
	sudo docker build -t pwittchen/ubuntu-java9 .
cli:
	sudo docker run -i -t pwittchen/ubuntu-java9
remove:
	../remove_container.sh pwittchen/ubuntu-java9
push:
	sudo docker push pwittchen/ubuntu-java9
pull:
	sudo docker pull pwittchen/ubuntu-java9
list:
	sudo docker images
