build:
	sudo docker build -t pwittchen/ubuntu-java12 .
cli:
	sudo docker run -i -t pwittchen/ubuntu-java12
remove:
	../remove_container.sh pwittchen/ubuntu-java12
push:
	sudo docker push pwittchen/ubuntu-java12
pull:
	sudo docker pull pwittchen/ubuntu-java12
list:
	sudo docker images
