build:
	sudo docker build -t pwittchen/alpine-java11 .
cli:
	sudo docker run -i -t pwittchen/alpine-java11
remove:
	../remove_container.sh pwittchen/alpine-java11
push:
	sudo docker push pwittchen/alpine-java11
pull:
	sudo docker pull pwittchen/alpine-java11
list:
	sudo docker images
