build:
	sudo docker build -t pwittchen/ubuntu-java10 .
cli:
	sudo docker run -i -t pwittchen/ubuntu-java10
remove:
	../remove_container.sh pwittchen/ubuntu-java10
push:
	sudo docker push pwittchen/ubuntu-java10
pull:
	sudo docker pull pwittchen/ubuntu-java10
list:
	sudo docker images
