build:
	sudo docker build -t pwittchen/ubuntu-java11-sapmachine .
cli:
	sudo docker run -i -t pwittchen/ubuntu-java11-sapmachine
remove:
	../remove_container.sh pwittchen/ubuntu-java11-sapmachine
push:
	sudo docker push pwittchen/ubuntu-java11-sapmachine
pull:
	sudo docker pull pwittchen/ubuntu-java11-sapmachine
list:
	sudo docker images
