build:
	sudo docker build -t pwittchen/alpine-sapmachine .
cli:
	sudo docker run -i -t pwittchen/alpine-sapmachine
remove:
	../remove_container.sh pwittchen/alpine-sapmachine
push:
	sudo docker push pwittchen/alpine-sapmachine
pull:
	sudo docker pull pwittchen/alpine-sapmachine
list:
	sudo docker images
