build:
	sudo docker build -t pwittchen/alpine-java13 .
cli:
	sudo docker run -i -t pwittchen/alpine-java13
remove:
	../remove_container.sh pwittchen/alpine-java13
push:
	sudo docker push pwittchen/alpine-java13
pull:
	sudo docker pull pwittchen/alpine-java13
list:
	sudo docker images
