build:
	sudo docker build -t pwittchen/ubuntu-java13 .
cli:
	sudo docker run -i -t pwittchen/ubuntu-java13
remove:
	../remove_container.sh pwittchen/ubuntu-java13
push:
	sudo docker push pwittchen/ubuntu-java13
pull:
	sudo docker pull pwittchen/ubuntu-java13
list:
	sudo docker images
