build:
	sudo docker build -t pwittchen/ubuntu-java8 .
cli:
	sudo docker run -i -t pwittchen/ubuntu-java8
remove:
	../remove_container.sh pwittchen/ubuntu-java8
push:
	sudo docker push pwittchen/ubuntu-java8
pull:
	sudo docker pull pwittchen/ubuntu-java8
list:
	sudo docker images
