build:
	sudo docker build -t pwittchen/alpine-java8 .
cli:
	sudo docker run -i -t pwittchen/alpine-java8
remove:
	../remove_container.sh pwittchen/alpine-java8
push:
	sudo docker push pwittchen/alpine-java8
pull:
	sudo docker pull pwittchen/alpine-java8
list:
	sudo docker images
