build:
	sudo docker build -t alpine-java8 .
cli:
	sudo docker run -i -t alpine-java8
remove:
	../remove_container.sh alpine-java8
list:
	sudo docker images
pull:
	sudo docker pull pwittchen/alpine-java8
cli_pulled:
	sudo docker run -i -t pwittchen/alpine-java8
