build:
	sudo docker build -t pwittchen/ubuntu-graalvm .
cli:
	sudo docker run -i -t pwittchen/ubuntu-graalvm
remove:
	../remove_container.sh pwittchen/ubuntu-graalvm
push:
	sudo docker push pwittchen/ubuntu-graalvm
pull:
	sudo docker pull pwittchen/ubuntu-graalvm
list:
	sudo docker images
