build:
	sudo docker build -t pwittchen/alpine-java12 .
cli:
	sudo docker run -i -t pwittchen/alpine-java12
remove:
	../remove_container.sh pwittchen/alpine-java12
push:
	sudo docker push pwittchen/alpine-java12
pull:
	sudo docker pull pwittchen/alpine-java12
list:
	sudo docker images
