build:
	sudo docker build -t pwittchen/ubuntu-java11 .
cli:
	sudo docker run -i -t pwittchen/ubuntu-java11
remove:
	../remove_container.sh pwittchen/ubuntu-java11
push:
	sudo docker push pwittchen/ubuntu-java11
pull:
	sudo docker pull pwittchen/ubuntu-java11
list:
	sudo docker images
