build:
	sudo docker build -t ubuntu-java11 .
cli:
	sudo docker run -i -t ubuntu-java11
remove:
	../remove_container.sh ubuntu-java11
push:
	sudo docker push pwittchen/ubuntu-java11
pull:
	sudo docker pull pwittchen/ubuntu-java11
list:
	sudo docker images
